version: "3.0"
services:
    redis:
        image: redis:6.2.4
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    redis-data:
        external: false